language: node_js
node_js:
  - "9"

addons:
  postgresql: "9.5"

services:
  - postgresql

env:
  global:
  - NABU=$(pwd)
  - NODE_ENV=TEST

before_install:
  - npm install -g npm@5.7.0
  - npm install -g npm@5.7.0

install:
  - npm install # note: cannot use npm ci as it will remove flyway
  - rm node_modules/.bin/flyway
  - cd node_modules/.bin && ln -s ../flyway/lib/flyway-5.0.7/flyway flyway && cd - # re-link Flyway after npm install
  - ls -lh node_modules/.bin
  - npm install -g snyk

before_script:
  - psql -c "create database qcdb_test;" -U postgres
  - psql qcdb_test -U postgres < test/migrations/create_test_fileqc.sql
  - npm run fw:test-migrate
  - cd test && sqlite3 fpr.db < migrations/create_test_fpr.sql && cd ..

script: 
  - snyk test
  - npm run lint
  - npm run test

cache:
  directories:
    - "node_modules"
