language: node_js
node_js:
  - "9"
  - "10"

addons:
  postgresql: "9.5"

services:
  - postgresql
  - docker

env:
  global:
  - NABU=$(pwd)
  - NODE_ENV=TEST

before_install:
  - npm install -g npm@5.7.0
  - docker pull boxfuse/flyway

install:
  - npm install

before_script:
  - psql -c "create database qcdb_test;" -U postgres
  - psql qcdb_test -U postgres < test/create_test_fileqc.sql
  - cp test/example-flyway.conf test/flyway.conf

script: 
  - npm run lint
  - npm run test

cache:
  directories:
    - "node_modules"
