language: node_js
node_js:
  - "10"

addons:
  postgresql: "9.5"

services:
  - postgresql

env:
  global:
  - NABU=$(pwd)
  - NODE_ENV=TEST

install:
  - npm install

before_script:
  - psql -c "create user test; alter role test with password 'test';" -U postgres
  - psql -c "create database qcdb_test with owner test;" -U postgres

script: 
  - npm run lint
  - npm run test

cache:
  directories:
    - "node_modules"
